version: '3.4'

services:
  rabbitmq:
    ports:
      - "15672:15672"

  ghm.filemanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - default
      - website-network
    ports:
      - "50005:80"

  ghm.web.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - default
      - website-network
    ports:
      - "50008:80"


  ghm.authentication:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - default
      - website-network
    ports:
      - "50000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  ghm.core.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - default
      - website-network
    ports:
      - "50001:80"


  ghm.website.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - default
      - website-network
    ports:
      - "50002:80"


  ghm.notifications.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - default
      - website-network
    ports:
      - "50004:80"

  ghm.website.nelly:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - default
      - website-network
    ports:
      - "9200:80"

networks:
  website-network:
    external: true


