version: '3.4'

services:
  rabbitmq:
    ports:
      - "15672:15672"

  filemanagement-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - default
      - website-network
    ports:
      - "50005:80"

  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - default
      - website-network
    ports:
      - "50008:80"


  authentication:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - default
      - website-network
    ports:
      - "50000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  core-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - default
      - website-network
    ports:
      - "50001:80"


  website-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - default
      - website-network
    ports:
      - "50002:80"


  notifications-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - default
      - website-network
    ports:
      - "50004:80"

  website-nelly:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - default
      - website-network
    ports:
      - "9200:80"

networks:
  default:
    driver: bridge
  website-network:
    external: true


