version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3.7.7-management-alpine
    ports:
      - 15672:15672

  ghm.filemanagement.api:
    image: ${DOCKER_REGISTRY-}ghmfilemanagementapi
    build:
      context: .
      dockerfile: GHM.FileManagement.Api/Dockerfile

  ghm.web.apigateway:
    image: ${DOCKER_REGISTRY-}ghmwebapigateway
    build:
      context: .
      dockerfile: GHM.Web.ApiGateway/Dockerfile
    depends_on:
    - rabbitmq

  ghm.authentication:
    image: ${DOCKER_REGISTRY-}ghmauthentication
    build:
      context: .
      dockerfile: GHM.Authentication/Dockerfile
    depends_on:
    - rabbitmq


  ghm.core.api:
    image: ${DOCKER_REGISTRY-}ghmcoreapi
    build:
      context: .
      dockerfile: GHM.Core.Api/Dockerfile
    depends_on:
    - rabbitmq

  ghm.website.api:
    image: ${DOCKER_REGISTRY-}ghmwebsiteapi
    build:
      context: .
      dockerfile: GHM.Website.Api/Dockerfile
    depends_on:
    - rabbitmq

  ghm.notifications.api:
    image: ${DOCKER_REGISTRY-}ghmnotificationsapi
    build:
      context: .
      dockerfile: GHM.Notifications.Api/Dockerfile
    depends_on:
    - rabbitmq

  ghm.website.nelly:
    image: ${DOCKER_REGISTRY-}ghmwebsitenelly
    build:
      context: .
      dockerfile: GHM.WebSite.Nelly/Dockerfile

