version: '3.4'

services:
  filemanagement-api:
    image: ${DOCKER_REGISTRY-}ghmfilemanagementapi
    build:
      context: .
      dockerfile: GHM.FileManagement.Api/Dockerfile

  apigateway:
    image: ${DOCKER_REGISTRY-}ghmwebapigateway
    build:
      context: .
      dockerfile: GHM.Web.ApiGateway/Dockerfile
    depends_on:
      - rabbitmq
      - authentication
      - core-api
      - warehouse-api
      - website-event-api
      - filemanagement-api
      - notifications-api

  authentication:
    image: ${DOCKER_REGISTRY-}ghmauthentication
    build:
      context: .
      dockerfile: GHM.Authentication/Dockerfile
    depends_on:
      - rabbitmq

  core-api:
    image: ${DOCKER_REGISTRY-}ghmcoreapi
    build:
      context: .
      dockerfile: GHM.Core.Api/Dockerfile
    depends_on:
      - rabbitmq
      - authentication

  website-api:
    image: ${DOCKER_REGISTRY-}ghmwebsiteapi
    build:
      context: .
      dockerfile: GHM.Website.Api/Dockerfile
    depends_on:
      - rabbitmq
      - authentication

  notifications-api:
    image: ${DOCKER_REGISTRY-}ghmnotificationsapi
    build:
      context: .
      dockerfile: GHM.Notifications.Api/Dockerfile
    depends_on:
      - rabbitmq
      - authentication

  website-nelly:
    image: ${DOCKER_REGISTRY-}ghmwebsitenelly
    build:
      context: .
      dockerfile: GHM.WebSite.Nelly/Dockerfile
    depends_on:
      - rabbitmq
      - authentication

  website-event-api:
    image: ${DOCKER_REGISTRY-}ghmwebsiteeventapi
    build:
      context: .
      dockerfile: GHM.Website.Event.Api/Dockerfile
    depends_on:
      - rabbitmq
      - authentication

  warehouse-api:
    image: ${DOCKER_REGISTRY-}ghmwarehouseapi
    build:
      context: .
      dockerfile: GHM.Warehouse.Api/Dockerfile
    depends_on:
      - rabbitmq
      - authentication

  rabbitmq:
    image: rabbitmq:3.7.7-management-alpine
    ports:
      - 5673:5672


  mssql-data:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 123@123a
    ports:
      - 1434:1433
    volumes:
      - mssql-data:/var/opt/mssql/data

volumes:
  mssql-data:
      external: true

