version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3.7.7-management-alpine
    ports:
      - 15672:15672

  filemanagement-api:
    image: ${DOCKER_REGISTRY-}ghmfilemanagementapi
    build:
      context: .
      dockerfile: GHM.FileManagement.Api/Dockerfile
    depends_on:
      - authentication

  apigateway:
    image: ${DOCKER_REGISTRY-}ghmwebapigateway
    build:
      context: .
      dockerfile: GHM.Web.ApiGateway/Dockerfile
    depends_on:
      - rabbitmq
      - authentication
      - core-api

  authentication:
    image: ${DOCKER_REGISTRY-}ghmauthentication
    build:
      context: .
      dockerfile: GHM.Authentication/Dockerfile
    depends_on:
      - rabbitmq


  core-api:
    image: ${DOCKER_REGISTRY-}ghmcoreapi
    build:
      context: .
      dockerfile: GHM.Core.Api/Dockerfile
    depends_on:
      - rabbitmq
      - authentication

  website-api:
    image: ${DOCKER_REGISTRY-}ghmwebsiteapi
    build:
      context: .
      dockerfile: GHM.Website.Api/Dockerfile
    depends_on:
      - rabbitmq
      - authentication

  notifications-api:
    image: ${DOCKER_REGISTRY-}ghmnotificationsapi
    build:
      context: .
      dockerfile: GHM.Notifications.Api/Dockerfile
    depends_on:
    - rabbitmq
    - authentication

  website-nelly:
    image: ${DOCKER_REGISTRY-}ghmwebsitenelly
    build:
      context: .
      dockerfile: GHM.WebSite.Nelly/Dockerfile
    depends_on:
      - authentication

