version: '3'

services:
  ghm.authentication:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  ghm.core.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat

