//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHM.Website.JadesSpa.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GHM.WebSite.JadesSpa.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Coursers.
        /// </summary>
        public static string AllCourses {
            get {
                return ResourceManager.GetString("AllCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jade Spa systems.
        /// </summary>
        public static string AngencySystem {
            get {
                return ResourceManager.GetString("AngencySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưng nhận về an toàn chất lượng.
        /// </summary>
        public static string CertificateSafeAmiea {
            get {
                return ResourceManager.GetString("CertificateSafeAmiea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get in Touch.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Pyrexar.
        /// </summary>
        public static string ContactPyrexar {
            get {
                return ResourceManager.GetString("ContactPyrexar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter content.
        /// </summary>
        public static string ContentPlaceHolder {
            get {
                return ResourceManager.GetString("ContentPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Contents {
            get {
                return ResourceManager.GetString("Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;We filter best services to serve for you&quot;.
        /// </summary>
        public static string DescriptionHot {
            get {
                return ResourceManager.GetString("DescriptionHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We filter best services and product to serve you.
        /// </summary>
        public static string DescriptionIntroduce {
            get {
                return ResourceManager.GetString("DescriptionIntroduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection of Hyperthermia Videos from various sources.
        /// </summary>
        public static string DescriptionVideo {
            get {
                return ResourceManager.GetString("DescriptionVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Agents.
        /// </summary>
        public static string DistributionAgents {
            get {
                return ResourceManager.GetString("DistributionAgents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email.
        /// </summary>
        public static string EmailPlaceHolder {
            get {
                return ResourceManager.GetString("EmailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string EquipmentIntroduce {
            get {
                return ResourceManager.GetString("EquipmentIntroduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Detail.
        /// </summary>
        public static string EventDetail {
            get {
                return ResourceManager.GetString("EventDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Image.
        /// </summary>
        public static string EventImage {
            get {
                return ResourceManager.GetString("EventImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Introduction.
        /// </summary>
        public static string EventIntroduction {
            get {
                return ResourceManager.GetString("EventIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professionals Join.
        /// </summary>
        public static string EventProfessionals {
            get {
                return ResourceManager.GetString("EventProfessionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive brand in Vietnam.
        /// </summary>
        public static string ExclusiveBrand {
            get {
                return ResourceManager.GetString("ExclusiveBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert Team.
        /// </summary>
        public static string ExpertTeamIntroductuce {
            get {
                return ResourceManager.GetString("ExpertTeamIntroductuce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder.
        /// </summary>
        public static string Founder {
            get {
                return ResourceManager.GetString("Founder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter full name.
        /// </summary>
        public static string FullNamePlaceHolder {
            get {
                return ResourceManager.GetString("FullNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string HomePhone {
            get {
                return ResourceManager.GetString("HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOTLINE.
        /// </summary>
        public static string HotLine {
            get {
                return ResourceManager.GetString("HotLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure.
        /// </summary>
        public static string InfrastructureIntroduce {
            get {
                return ResourceManager.GetString("InfrastructureIntroduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Library.
        /// </summary>
        public static string LibraryImage {
            get {
                return ResourceManager.GetString("LibraryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nelly De Vuyst for the development of the beauty industry in Vietnam.
        /// </summary>
        public static string NellyProgress {
            get {
                return ResourceManager.GetString("NellyProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Hot.
        /// </summary>
        public static string NewsHot {
            get {
                return ResourceManager.GetString("NewsHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Related.
        /// </summary>
        public static string NewsRelated {
            get {
                return ResourceManager.GetString("NewsRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;We are happy when sharing with you about beauty &amp; life story&quot;.
        /// </summary>
        public static string NewSuggestionDesciption {
            get {
                return ResourceManager.GetString("NewSuggestionDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News &amp; Experience.
        /// </summary>
        public static string NewSuggestionTitle {
            get {
                return ResourceManager.GetString("NewSuggestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter phone number.
        /// </summary>
        public static string PhoneNumberPlaceHolder {
            get {
                return ResourceManager.GetString("PhoneNumberPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional.
        /// </summary>
        public static string Professionals {
            get {
                return ResourceManager.GetString("Professionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định hướng phát triển.
        /// </summary>
        public static string ProgressAmiea {
            get {
                return ResourceManager.GetString("ProgressAmiea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Blogs.
        /// </summary>
        public static string RecentBlogs {
            get {
                return ResourceManager.GetString("RecentBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Now.
        /// </summary>
        public static string RegisterNows {
            get {
                return ResourceManager.GetString("RegisterNows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer&apos;s Feeling.
        /// </summary>
        public static string ResponseCustomer {
            get {
                return ResourceManager.GetString("ResponseCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seminar.
        /// </summary>
        public static string Seminars {
            get {
                return ResourceManager.GetString("Seminars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Mesage.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string ServicesIntroduce {
            get {
                return ResourceManager.GetString("ServicesIntroduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Spa.
        /// </summary>
        public static string SpaceSpa {
            get {
                return ResourceManager.GetString("SpaceSpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsors.
        /// </summary>
        public static string Sponsors {
            get {
                return ResourceManager.GetString("Sponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian diễn ra sự kiện.
        /// </summary>
        public static string TimeEvent {
            get {
                return ResourceManager.GetString("TimeEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Number One about Massage Pregnant &amp; Take care of Nascency&quot;.
        /// </summary>
        public static string TitleDescription {
            get {
                return ResourceManager.GetString("TitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Jade spa.
        /// </summary>
        public static string TitleHeader {
            get {
                return ResourceManager.GetString("TitleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Services.
        /// </summary>
        public static string TitleHot {
            get {
                return ResourceManager.GetString("TitleHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why shoul you chose Jade Spa.
        /// </summary>
        public static string TitleIntroduce {
            get {
                return ResourceManager.GetString("TitleIntroduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Library.
        /// </summary>
        public static string VideoLibrary {
            get {
                return ResourceManager.GetString("VideoLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Detail.
        /// </summary>
        public static string ViewDetail {
            get {
                return ResourceManager.GetString("ViewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View more.
        /// </summary>
        public static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Product.
        /// </summary>
        public static string ViewProduct {
            get {
                return ResourceManager.GetString("ViewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to why is organic.
        /// </summary>
        public static string WhyIsOrganic {
            get {
                return ResourceManager.GetString("WhyIsOrganic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four reasons why hollygood stars are sure to choose nelly&apos;s products.
        /// </summary>
        public static string WhySelectNellyDeVuyst {
            get {
                return ResourceManager.GetString("WhySelectNellyDeVuyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Time.
        /// </summary>
        public static string WorkTime {
            get {
                return ResourceManager.GetString("WorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Needs.
        /// </summary>
        public static string YourNeeds {
            get {
                return ResourceManager.GetString("YourNeeds", resourceCulture);
            }
        }
    }
}
