// <auto-generated />
using System;
using GHM.Notifications.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GHM.Notifications.Api.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20180624140155_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GHM.Notifications.Api.Infrastructure.Models.Notification", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(50);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Image");

                    b.Property<bool>("IsDelete");

                    b.Property<bool>("IsRead");

                    b.Property<bool>("IsShow");

                    b.Property<DateTime?>("LastUpdate");

                    b.Property<DateTime?>("ReadTime");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("SenderAvatar")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("SenderFullName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<int>("Type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GHM.Notifications.Api.Infrastructure.Models.UserConnection", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(50);

                    b.Property<string>("ConnectionId")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreateTime");

                    b.HasKey("UserName", "ConnectionId");

                    b.ToTable("UserConnections");
                });
#pragma warning restore 612, 618
        }
    }
}
